EPMRPP-67754: support custom statuses for launch & items
reportportal/agent-js-playwright pull request #11
Opened 2021-11-01 13:37 UTC by oranje322

2021-11-01 14:04 UTC, chivekrodis requested changes

2021-11-01 14:04 UTC, chivekrodis commented on src/reporter.ts
> +  setStatus(status: string, test: TestCase, suite: string): void {
Method `setStatus` should accept only statuses from  type RP_STATUSES, not custom or just string

2021-11-01 14:04 UTC, chivekrodis commented on src/reportingApi.ts
> +  setStatusPassed: (suite?: string) =>
Please provide methods like `setStatus` and` setLaunchStatus` where user can pass status by self

2021-11-01 16:57 UTC, chivekrodis approved these changes

2021-11-02 08:12 UTC, AmsterGet commented on src/reporter.ts
> +      status: status ? status : result.status,
Can be simplified:
`status || result.status`

2021-11-02 08:23 UTC, AmsterGet approved these changes

2021-11-02 08:23 UTC, merged