EPMRPP-68602 || report logs with/without attachments
reportportal/agent-js-playwright pull request #12
Opened 2021-11-26 14:34 UTC by oranje322

2021-11-29 09:21 UTC, AmsterGet requested changes

2021-11-29 10:55 UTC, oranje322 commented on src/reporter.ts
> +      this.launchLogs.set(log.message, log);
We need this to avoid sending logs again. These methods are executed for each run of the test.

2021-11-29 13:41 UTC, chivekrodis requested changes

2021-11-29 13:41 UTC, chivekrodis commented on src/reporter.ts
> +    for (const [key, value] of this.launchLogs) {
What the reason iterate here every time if `launchLog` is a `Map` with keys = `log.message`?
Looks like `findLaunchLog` is redundant.

2021-11-29 13:41 UTC, chivekrodis commented on src/reporter.ts
> +        `\n\`\`\`error\n${result.error.message}\n\`\`\``,
Should we provide just message or full log into description? Logs in description and in the test are not the same

2021-11-29 13:41 UTC, chivekrodis commented on src/reportingApi.ts
> +    level: LOG_LEVELS | string = LOG_LEVELS.INFO,
level should be one of `LOG_LEVELS` not just any string

2021-11-29 17:37 UTC, chivekrodis reviewed
Please fix linter errors

2021-11-30 07:30 UTC, chivekrodis approved these changes

2021-11-30 07:37 UTC, AmsterGet approved these changes

2021-11-30 07:37 UTC, merged