EPMRPP-69207 || add retries reporting support
reportportal/agent-js-playwright pull request #14
Opened 2021-12-02 14:11 UTC by oranje322

2021-12-02 14:23 UTC, AmsterGet requested changes
Also please add corresponding tests to cover this feature.

2021-12-02 14:23 UTC, AmsterGet commented on examples/tests/statusesTest.spec.ts
> +    expect(false).toBe(true);
Why are you update these examples?
It was nice to see that our `ReportingApi` method will change the test status to another.

2021-12-02 14:23 UTC, AmsterGet commented on examples/tests/statusesTest.spec.ts
> +    expect(true).toBe(true);
Same here

2021-12-06 07:14 UTC, chivekrodis approved these changes

2021-12-06 08:26 UTC, AmsterGet approved these changes

2021-12-06 08:26 UTC, merged