EPMRPP-65579: get information to system attr & skippedIssue report
reportportal/agent-js-playwright pull request #3
Opened 2021-09-13 09:26 UTC by oranje322

2021-09-13 10:05 UTC, chivekrodis requested changes

2021-09-15 10:26 UTC, chivekrodis approved these changes

2021-09-15 21:46 UTC, AmsterGet requested changes

2021-09-15 21:46 UTC, AmsterGet commented on src/reporter.ts
> +    if (result.status === 'skipped') {
Please use the status constant.

2021-09-16 14:55 UTC, AmsterGet approved these changes

2021-09-16 14:57 UTC, merged