EPMRPP-73983 || Finish suites after childrens
reportportal/agent-js-playwright pull request #36
Opened 2022-03-15 14:28 UTC by oranje322

2022-03-21 08:11 UTC, chivekrodis requested changes

2022-03-21 08:11 UTC, chivekrodis commented on src/__tests__/reporter/logReporting.spec.ts
> +        ['projectName', { id: 'tempTestItemId', name: 'projectName', testsLength: 0 }],
Maybe better move all strings into constants to reuse it

2022-03-22 07:00 UTC, chivekrodis approved these changes

2022-03-22 08:56 UTC, AmsterGet approved these changes

2022-03-22 08:57 UTC, merged