Epmrpp 76809 same filename error
reportportal/agent-js-playwright pull request #48
Opened 2022-05-16 11:37 UTC by oranje322

2022-05-16 15:07 UTC, chivekrodis requested changes

2022-05-16 15:07 UTC, chivekrodis commented on src/reporter.ts
> +    const decreaseIndex = test.retries > 0 && result.status === 'passed' ? test.retries + 1 : 1;
`decreaseIndex` sound like an action however it is value

2022-05-16 15:07 UTC, chivekrodis commented on src/utils.ts
> +export const getTestFilePath = (testItem: testItemPick, itemTitle: string): string => {
Please cover this function with a tests

2022-05-17 09:11 UTC, chivekrodis approved these changes

2022-05-17 09:20 UTC, AmsterGet approved these changes

2022-05-17 09:20 UTC, merged